
description: Feel free to bookmark this to keep an eye on my project up



defaults:
  -
    scope:
      path: "" 
    values:
        tags: "present"

gems: 
      - jekyll-sitemap
        
        